services:
  - postgresql

env:
  - JWT_SECRET=secret NODE_ENV=test

cache:
  - directories:
    - $HOME/.yarn/

matrix:
  include:
    - language: node
      before_script:
        - cd backend
        - nvm install
        - nvm use
        - npm install -g yarn
        - yarn install
        - psql -c 'create database test;' -U postgres
        - yarn run migrate
      script:
        - yarn test
