services:
  - postgresql

env:
  - JWT_SECRET=secret NODE_ENV=test

cache:
  - directories:
    - $HOME/.yarn/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

matrix:
  include:
    - language: node
      before_script:
        - cd backend
        - nvm install
        - nvm use
        - npm install -g yarn
        - yarn install
        - psql -c 'create database test;' -U postgres
        - yarn run migrate
      script:
        - yarn typecheck
        - yarn test

    - language: android
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - android-22
          - sys-img-armeabi-v7a-android-22
      before_script:
        - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - cd android
        - ./gradlew connectedAndroidTest
